import type {
  Venue,
  VenueAccessibilityDetails,
  Review,
  ReviewPhoto,
  Profile,
  VenuePhoto,
  MobilityTip,
} from "@/types/database";

// Profiles
export const profiles: Profile[] = [
  {
    id: "profile-matthew",
    display_name: "Matthew Brothers",
    bio: "Accessibility consultant, TBI survivor, and scooter user. 30 years navigating the world with a spastic gait. I review venues so you know what you're getting into before you get there.",
    avatar_url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop",
    mobility_profile: ["scooter", "gait_disorder"],
    home_city: "Maysville, KY",
    is_editor: true,
    is_admin: false,
    review_count: 3,
    created_at: "2026-01-01T00:00:00Z",
  },
  {
    id: "profile-brad",
    display_name: "Brad Eilerman",
    bio: "Co-founder. Physician and technologist based in Northern Kentucky.",
    avatar_url: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop",
    mobility_profile: [],
    home_city: "Northern Kentucky",
    is_editor: false,
    is_admin: true,
    review_count: 0,
    created_at: "2026-01-01T00:00:00Z",
  },
];

// Venues
export const venues: Venue[] = [
  {
    id: "venue-braxton",
    name: "Braxton Brewing Company",
    slug: "braxton-brewing-company",
    address_line1: "27 W 7th St",
    city: "Covington",
    state: "KY",
    zip: "41011",
    latitude: 39.0837,
    longitude: -84.5084,
    category: "bar_brewery",
    overall_rating: "partially_accessible",
    has_editorial_review: true,
    featured: true,
    created_at: "2026-01-15T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "venue-aquarium",
    name: "Newport Aquarium",
    slug: "newport-aquarium",
    address_line1: "1 Levee Way",
    city: "Newport",
    state: "KY",
    zip: "41071",
    latitude: 39.0953,
    longitude: -84.4969,
    category: "entertainment",
    website: "https://www.newportaquarium.com",
    overall_rating: "accessible",
    has_editorial_review: true,
    featured: true,
    created_at: "2026-01-20T00:00:00Z",
    updated_at: "2026-03-05T00:00:00Z",
  },
  {
    id: "venue-roebling",
    name: "Roebling Point Books & Coffee",
    slug: "roebling-point-books-coffee",
    address_line1: "306 Greenup St",
    city: "Covington",
    state: "KY",
    zip: "41011",
    latitude: 39.0866,
    longitude: -84.5097,
    category: "coffee_shop",
    overall_rating: "partially_accessible",
    has_editorial_review: true,
    featured: false,
    created_at: "2026-02-01T00:00:00Z",
    updated_at: "2026-03-10T00:00:00Z",
  },
  {
    id: "venue-blinkers",
    name: "Blinker's Tavern",
    slug: "blinkers-tavern",
    address_line1: "318 Greenup St",
    city: "Covington",
    state: "KY",
    zip: "41011",
    latitude: 39.0869,
    longitude: -84.5099,
    category: "restaurant",
    overall_rating: "not_accessible",
    has_editorial_review: false,
    featured: false,
    created_at: "2026-02-05T00:00:00Z",
    updated_at: "2026-02-05T00:00:00Z",
  },
  {
    id: "venue-st-elizabeth",
    name: "St. Elizabeth Hospital - Edgewood",
    slug: "st-elizabeth-hospital-edgewood",
    address_line1: "1 Medical Village Dr",
    city: "Edgewood",
    state: "KY",
    zip: "41017",
    latitude: 39.0186,
    longitude: -84.5618,
    category: "hospital",
    website: "https://www.stelizabeth.com",
    overall_rating: "accessible",
    has_editorial_review: false,
    featured: false,
    created_at: "2026-02-10T00:00:00Z",
    updated_at: "2026-02-10T00:00:00Z",
  },
  {
    id: "venue-gabp",
    name: "Great American Ball Park",
    slug: "great-american-ball-park",
    address_line1: "100 Joe Nuxhall Way",
    city: "Cincinnati",
    state: "OH",
    zip: "45202",
    latitude: 39.0974,
    longitude: -84.5065,
    category: "sports_venue",
    website: "https://www.mlb.com/reds/ballpark",
    overall_rating: "accessible",
    has_editorial_review: false,
    featured: false,
    created_at: "2026-02-15T00:00:00Z",
    updated_at: "2026-02-15T00:00:00Z",
  },
  {
    id: "venue-cvg",
    name: "Cincinnati/Northern Kentucky Airport (CVG)",
    slug: "cvg-airport",
    address_line1: "3087 Terminal Dr",
    city: "Hebron",
    state: "KY",
    zip: "41048",
    latitude: 39.0488,
    longitude: -84.6678,
    category: "transportation",
    website: "https://www.cvgairport.com",
    overall_rating: "accessible",
    has_editorial_review: false,
    featured: false,
    created_at: "2026-02-20T00:00:00Z",
    updated_at: "2026-02-20T00:00:00Z",
  },
  {
    id: "venue-findlay",
    name: "Findlay Market",
    slug: "findlay-market",
    address_line1: "1801 Race St",
    city: "Cincinnati",
    state: "OH",
    zip: "45202",
    latitude: 39.1153,
    longitude: -84.5189,
    category: "grocery",
    website: "https://www.findlaymarket.org",
    overall_rating: "partially_accessible",
    has_editorial_review: false,
    featured: false,
    created_at: "2026-02-25T00:00:00Z",
    updated_at: "2026-02-25T00:00:00Z",
  },
  {
    id: "venue-levee",
    name: "Newport on the Levee",
    slug: "newport-on-the-levee",
    address_line1: "1 Levee Way",
    city: "Newport",
    state: "KY",
    zip: "41071",
    latitude: 39.0948,
    longitude: -84.4963,
    category: "entertainment",
    website: "https://www.newportonthelevee.com",
    overall_rating: "accessible",
    has_editorial_review: false,
    featured: false,
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "venue-hofbrauhaus",
    name: "Hofbr\u00e4uhaus Newport",
    slug: "hofbrauhaus-newport",
    address_line1: "200 E 3rd St",
    city: "Newport",
    state: "KY",
    zip: "41071",
    latitude: 39.0919,
    longitude: -84.4947,
    category: "restaurant",
    website: "https://www.hofbrauhausnewport.com",
    overall_rating: "partially_accessible",
    has_editorial_review: false,
    featured: false,
    created_at: "2026-03-05T00:00:00Z",
    updated_at: "2026-03-05T00:00:00Z",
  },
  {
    id: "venue-devou",
    name: "Devou Park",
    slug: "devou-park",
    address_line1: "790 Park Ln",
    city: "Covington",
    state: "KY",
    zip: "41011",
    latitude: 39.0800,
    longitude: -84.5300,
    category: "park_trail",
    overall_rating: "not_accessible",
    has_editorial_review: false,
    featured: false,
    created_at: "2026-03-10T00:00:00Z",
    updated_at: "2026-03-10T00:00:00Z",
  },
  {
    id: "venue-mainstrasse",
    name: "MainStrasse Village",
    slug: "mainstrasse-village",
    address_line1: "Main St",
    city: "Covington",
    state: "KY",
    zip: "41011",
    latitude: 39.0852,
    longitude: -84.5114,
    category: "entertainment",
    overall_rating: "partially_accessible",
    has_editorial_review: false,
    featured: false,
    created_at: "2026-03-15T00:00:00Z",
    updated_at: "2026-03-15T00:00:00Z",
  },
];

// Accessibility Details
export const accessibilityDetails: VenueAccessibilityDetails[] = [
  {
    id: "ad-braxton",
    venue_id: "venue-braxton",
    has_accessible_parking: true,
    parking_notes: "Street parking and a small lot. One accessible spot in the lot, about 30 feet from the entrance.",
    parking_distance_to_entrance: "short",
    entrance_type: "ramp",
    entrance_door_width: "standard",
    entrance_has_automatic_door: false,
    entrance_ramp_slope: "moderate",
    entrance_notes: "Ramp exists but the door requires pulling toward you while backing up on the ramp. Manageable but awkward.",
    interior_floor_surface: "smooth",
    interior_aisle_width: "spacious",
    interior_has_elevator: false,
    interior_multiple_floors: false,
    interior_seating_options: "mixed",
    interior_table_height: "mixed",
    interior_notes: "Wide-open industrial space. Communal tables at good height. Some high-top tables mixed in.",
    bathroom_accessible: true,
    bathroom_stall_width: "adequate",
    bathroom_has_grab_bars: true,
    bathroom_door_width: "standard",
    bathroom_notes: "Grab bars present. Stall is tight for a scooter but workable for a wheelchair. Door swings inward which is the wrong direction.",
    scooter_maneuverable: true,
    scooter_charging_available: false,
    scooter_notes: "Plenty of room to navigate the main space. Impossible to charge — no accessible outlets.",
    staff_helpfulness: "good",
    noise_level: "moderate",
    lighting: "well_lit",
    last_verified_at: "2026-02-15T00:00:00Z",
    created_at: "2026-01-15T00:00:00Z",
    updated_at: "2026-02-15T00:00:00Z",
  },
  {
    id: "ad-aquarium",
    venue_id: "venue-aquarium",
    has_accessible_parking: true,
    parking_notes: "Large parking garage with multiple accessible spaces on each level, close to elevators.",
    parking_distance_to_entrance: "adjacent",
    entrance_type: "automatic_door",
    entrance_door_width: "wide",
    entrance_has_automatic_door: true,
    entrance_notes: "Fully automatic doors. Level entry from the parking garage. Main entrance also level.",
    interior_floor_surface: "smooth",
    interior_aisle_width: "spacious",
    interior_has_elevator: true,
    interior_multiple_floors: true,
    interior_seating_options: "flexible",
    interior_notes: "Excellent throughout. All exhibits accessible. Elevators between all levels. Viewing windows at multiple heights.",
    bathroom_accessible: true,
    bathroom_stall_width: "spacious",
    bathroom_has_grab_bars: true,
    bathroom_door_width: "wide",
    bathroom_notes: "Family/accessible restrooms available on every level. Spacious, clean, well-maintained.",
    scooter_maneuverable: true,
    scooter_charging_available: true,
    scooter_notes: "Scooter rentals available at the front desk. Charging station near the cafe. Wide paths throughout.",
    staff_helpfulness: "excellent",
    noise_level: "moderate",
    lighting: "mixed",
    last_verified_at: "2026-03-01T00:00:00Z",
    created_at: "2026-01-20T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "ad-roebling",
    venue_id: "venue-roebling",
    has_accessible_parking: false,
    parking_notes: "Street parking only. Nearest accessible spot is a block away on the main road.",
    parking_distance_to_entrance: "moderate",
    entrance_type: "steps_with_ramp",
    entrance_door_width: "narrow",
    entrance_has_automatic_door: false,
    entrance_ramp_slope: "steep",
    entrance_notes: "There's a small ramp to the side entrance, but it's steep and leads to a narrow door. The main entrance has two steps. Neither is great.",
    interior_floor_surface: "mixed",
    interior_aisle_width: "tight",
    interior_has_elevator: false,
    interior_multiple_floors: false,
    interior_seating_options: "mixed",
    interior_table_height: "standard",
    interior_notes: "Charming but cramped. Bookshelves create narrow aisles. Seating area near the window is the most accessible spot.",
    bathroom_accessible: false,
    bathroom_stall_width: "tight",
    bathroom_has_grab_bars: false,
    bathroom_door_width: "narrow",
    bathroom_notes: "Bathroom is down a narrow hallway. Door barely opens wide enough for a walker. Wheelchair or scooter? Forget it.",
    scooter_maneuverable: false,
    scooter_charging_available: false,
    scooter_notes: "Not scooter-friendly. The aisles between bookshelves are too narrow, and the side entrance ramp is too steep for safe use.",
    staff_helpfulness: "good",
    noise_level: "quiet",
    lighting: "dim",
    last_verified_at: "2026-02-28T00:00:00Z",
    created_at: "2026-02-01T00:00:00Z",
    updated_at: "2026-02-28T00:00:00Z",
  },
  {
    id: "ad-blinkers",
    venue_id: "venue-blinkers",
    has_accessible_parking: false,
    parking_notes: "Street parking only in a historic district. No accessible spots nearby.",
    parking_distance_to_entrance: "far",
    entrance_type: "steps_only",
    entrance_door_width: "standard",
    entrance_has_automatic_door: false,
    entrance_notes: "Three steps up to the entrance. No ramp. No alternative entrance. This is a historic building and they haven't addressed it.",
    interior_floor_surface: "uneven",
    interior_aisle_width: "tight",
    interior_has_elevator: false,
    interior_multiple_floors: false,
    interior_seating_options: "fixed_booth",
    interior_table_height: "standard",
    interior_notes: "Classic old tavern. If you can get in, the booths are fixed and narrow. Bar seating is the most accessible option.",
    bathroom_accessible: false,
    bathroom_stall_width: "tight",
    bathroom_has_grab_bars: false,
    bathroom_door_width: "narrow",
    bathroom_notes: "Down a narrow hallway. Not accessible by any standard.",
    scooter_maneuverable: false,
    scooter_charging_available: false,
    scooter_notes: "Cannot enter the building with a scooter. Period.",
    staff_helpfulness: "neutral",
    noise_level: "loud",
    lighting: "dim",
    last_verified_at: "2026-02-05T00:00:00Z",
    created_at: "2026-02-05T00:00:00Z",
    updated_at: "2026-02-05T00:00:00Z",
  },
  {
    id: "ad-st-elizabeth",
    venue_id: "venue-st-elizabeth",
    has_accessible_parking: true,
    parking_notes: "Abundant accessible parking at every entrance. Valet available at main entrance.",
    parking_distance_to_entrance: "adjacent",
    entrance_type: "automatic_door",
    entrance_door_width: "wide",
    entrance_has_automatic_door: true,
    entrance_notes: "Automatic doors at all entrances. Level entry throughout. This is a hospital — they get this right.",
    interior_floor_surface: "smooth",
    interior_aisle_width: "spacious",
    interior_has_elevator: true,
    interior_multiple_floors: true,
    interior_seating_options: "flexible",
    interior_notes: "Fully accessible throughout. Wide corridors. Clear signage. Elevators everywhere.",
    bathroom_accessible: true,
    bathroom_stall_width: "spacious",
    bathroom_has_grab_bars: true,
    bathroom_door_width: "wide",
    bathroom_notes: "Accessible restrooms on every floor. Clean, spacious, well-maintained.",
    scooter_maneuverable: true,
    scooter_charging_available: true,
    scooter_notes: "Scooter and wheelchair available for loan. Charging available. Wide corridors handle any mobility device.",
    staff_helpfulness: "excellent",
    noise_level: "quiet",
    lighting: "well_lit",
    last_verified_at: "2026-02-10T00:00:00Z",
    created_at: "2026-02-10T00:00:00Z",
    updated_at: "2026-02-10T00:00:00Z",
  },
  {
    id: "ad-gabp",
    venue_id: "venue-gabp",
    has_accessible_parking: true,
    parking_notes: "Multiple accessible lots. Lots A and C are closest. Pre-purchase recommended for game days.",
    parking_distance_to_entrance: "short",
    entrance_type: "level",
    entrance_door_width: "wide",
    entrance_has_automatic_door: true,
    entrance_notes: "Wide gates. Level entry. Staff available to assist at all gates.",
    interior_floor_surface: "smooth",
    interior_aisle_width: "spacious",
    interior_has_elevator: true,
    interior_multiple_floors: true,
    interior_seating_options: "flexible",
    interior_notes: "Accessible seating throughout the stadium. Companion seating available. Concourse is wide and smooth.",
    bathroom_accessible: true,
    bathroom_stall_width: "spacious",
    bathroom_has_grab_bars: true,
    bathroom_door_width: "wide",
    bathroom_notes: "Accessible restrooms on every level. Can get crowded on game days but facilities are well-designed.",
    scooter_maneuverable: true,
    scooter_charging_available: false,
    scooter_notes: "Scooter-friendly throughout the concourse. No charging stations found. Wide paths, gentle ramps between levels.",
    staff_helpfulness: "excellent",
    noise_level: "very_loud",
    lighting: "well_lit",
    last_verified_at: "2026-02-15T00:00:00Z",
    created_at: "2026-02-15T00:00:00Z",
    updated_at: "2026-02-15T00:00:00Z",
  },
  {
    id: "ad-cvg",
    venue_id: "venue-cvg",
    has_accessible_parking: true,
    parking_notes: "Accessible parking in all garages. Terminal garage has closest access to check-in.",
    parking_distance_to_entrance: "adjacent",
    entrance_type: "automatic_door",
    entrance_door_width: "wide",
    entrance_has_automatic_door: true,
    entrance_notes: "Automatic doors everywhere. Skybridge from garage is level and climate-controlled.",
    interior_floor_surface: "smooth",
    interior_aisle_width: "spacious",
    interior_has_elevator: true,
    interior_multiple_floors: true,
    interior_notes: "Post-renovation CVG is excellent. Smooth floors, wide concourses, clear wayfinding. Moving walkways throughout.",
    bathroom_accessible: true,
    bathroom_stall_width: "spacious",
    bathroom_has_grab_bars: true,
    bathroom_door_width: "wide",
    bathroom_notes: "Family restrooms available throughout. All restrooms have accessible stalls.",
    scooter_maneuverable: true,
    scooter_charging_available: true,
    scooter_notes: "Charging stations at gates. Wide concourses. Rental scooters available. This is as good as airports get.",
    staff_helpfulness: "excellent",
    noise_level: "moderate",
    lighting: "well_lit",
    last_verified_at: "2026-02-20T00:00:00Z",
    created_at: "2026-02-20T00:00:00Z",
    updated_at: "2026-02-20T00:00:00Z",
  },
  {
    id: "ad-findlay",
    venue_id: "venue-findlay",
    has_accessible_parking: true,
    parking_notes: "Small lot on Race St with 2 accessible spots. Street parking available but limited.",
    parking_distance_to_entrance: "short",
    entrance_type: "level",
    entrance_door_width: "wide",
    entrance_has_automatic_door: false,
    entrance_notes: "Main entrance is level and wide. No automatic doors but they're propped open during market hours.",
    interior_floor_surface: "uneven",
    interior_aisle_width: "tight",
    interior_has_elevator: false,
    interior_multiple_floors: false,
    interior_seating_options: "mixed",
    interior_notes: "Historic market building. Main aisles are decent but vendor areas get very tight, especially on weekends. Outdoor area is on cobblestone.",
    bathroom_accessible: true,
    bathroom_stall_width: "adequate",
    bathroom_has_grab_bars: true,
    bathroom_door_width: "standard",
    bathroom_notes: "Accessible restroom available. Adequate but showing its age. Grab bars present.",
    scooter_maneuverable: false,
    scooter_charging_available: false,
    scooter_notes: "Weekdays are manageable. Saturday morning market? You'll be stuck behind crowds in narrow aisles. The cobblestone outdoor area is rough on scooters.",
    staff_helpfulness: "good",
    noise_level: "loud",
    lighting: "well_lit",
    last_verified_at: "2026-02-25T00:00:00Z",
    created_at: "2026-02-25T00:00:00Z",
    updated_at: "2026-02-25T00:00:00Z",
  },
  {
    id: "ad-levee",
    venue_id: "venue-levee",
    has_accessible_parking: true,
    parking_notes: "Large garage with accessible spots on every level. Elevators to all levels.",
    parking_distance_to_entrance: "adjacent",
    entrance_type: "automatic_door",
    entrance_door_width: "wide",
    entrance_has_automatic_door: true,
    entrance_notes: "Automatic doors. Level entry from garage. All entrances are accessible.",
    interior_floor_surface: "smooth",
    interior_aisle_width: "spacious",
    interior_has_elevator: true,
    interior_multiple_floors: true,
    interior_notes: "Modern entertainment complex. Wide corridors, elevators between all levels. Individual restaurants and shops vary.",
    bathroom_accessible: true,
    bathroom_stall_width: "spacious",
    bathroom_has_grab_bars: true,
    bathroom_door_width: "wide",
    bathroom_notes: "Public restrooms are accessible. Individual restaurant restrooms vary.",
    scooter_maneuverable: true,
    scooter_charging_available: false,
    scooter_notes: "Common areas are great for scooters. Individual shops and restaurants may have tighter spaces.",
    staff_helpfulness: "good",
    noise_level: "moderate",
    lighting: "well_lit",
    last_verified_at: "2026-03-01T00:00:00Z",
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "ad-hofbrauhaus",
    venue_id: "venue-hofbrauhaus",
    has_accessible_parking: true,
    parking_notes: "Shared lot with a few accessible spots. Street parking available.",
    parking_distance_to_entrance: "short",
    entrance_type: "ramp",
    entrance_door_width: "wide",
    entrance_has_automatic_door: false,
    entrance_ramp_slope: "gentle",
    entrance_notes: "Gentle ramp to entrance. Doors are heavy but wide. Staff will help if you catch their eye.",
    interior_floor_surface: "smooth",
    interior_aisle_width: "adequate",
    interior_has_elevator: false,
    interior_multiple_floors: false,
    interior_seating_options: "mixed",
    interior_table_height: "standard",
    interior_notes: "Large open beer hall. Long communal tables are at good height. Getting to a seat in the middle of a bench is the challenge. Request an end seat.",
    bathroom_accessible: true,
    bathroom_stall_width: "adequate",
    bathroom_has_grab_bars: true,
    bathroom_door_width: "standard",
    bathroom_notes: "Accessible stall available. Adequate but not spacious. Grab bars present.",
    scooter_maneuverable: true,
    scooter_charging_available: false,
    scooter_notes: "The main hall has enough space. The biergarten outside is accessible too. Just request an end-of-bench seat.",
    staff_helpfulness: "good",
    noise_level: "very_loud",
    lighting: "well_lit",
    last_verified_at: "2026-03-05T00:00:00Z",
    created_at: "2026-03-05T00:00:00Z",
    updated_at: "2026-03-05T00:00:00Z",
  },
  {
    id: "ad-devou",
    venue_id: "venue-devou",
    has_accessible_parking: true,
    parking_notes: "Accessible spots at the overlook and golf course. Other areas have gravel or grass parking.",
    parking_distance_to_entrance: "adjacent",
    entrance_type: "level",
    entrance_door_width: "wide",
    entrance_has_automatic_door: false,
    entrance_notes: "No building entrance per se. The overlook has a paved path from the parking lot. Trails are a different story.",
    interior_floor_surface: "uneven",
    interior_aisle_width: "spacious",
    interior_notes: "The overlook area and main pavilion are paved and accessible. Most trails are gravel, dirt, or grass — not suitable for wheels.",
    bathroom_accessible: true,
    bathroom_stall_width: "adequate",
    bathroom_has_grab_bars: false,
    bathroom_door_width: "standard",
    bathroom_notes: "Restrooms near the overlook. Basic park facilities. No grab bars. Adequate width.",
    scooter_maneuverable: false,
    scooter_charging_available: false,
    scooter_notes: "The overlook loop is the only scooter-friendly area. Everything else is unpaved trails. Beautiful views but limited access.",
    staff_helpfulness: "neutral",
    noise_level: "quiet",
    lighting: "well_lit",
    last_verified_at: "2026-03-10T00:00:00Z",
    created_at: "2026-03-10T00:00:00Z",
    updated_at: "2026-03-10T00:00:00Z",
  },
  {
    id: "ad-mainstrasse",
    venue_id: "venue-mainstrasse",
    has_accessible_parking: true,
    parking_notes: "Small public lot on Main St. A couple accessible spots. Street parking is limited.",
    parking_distance_to_entrance: "short",
    entrance_type: "level",
    entrance_door_width: "wide",
    entrance_notes: "Outdoor shopping/dining district. Sidewalks are the 'entrance.' Most are level but narrow in spots.",
    interior_floor_surface: "mixed",
    interior_aisle_width: "adequate",
    interior_notes: "It's a village of shops and restaurants. Sidewalks are generally smooth but some brick sections. Individual businesses vary widely.",
    bathroom_accessible: false,
    bathroom_notes: "No public restrooms. Individual businesses vary. Most are small historic buildings with non-accessible restrooms.",
    scooter_maneuverable: true,
    scooter_charging_available: false,
    scooter_notes: "Sidewalks are manageable on a scooter. The brick sections are bumpy. Individual shops are often too small. Best for outdoor dining and walking the strip.",
    staff_helpfulness: "good",
    noise_level: "moderate",
    lighting: "well_lit",
    last_verified_at: "2026-03-15T00:00:00Z",
    created_at: "2026-03-15T00:00:00Z",
    updated_at: "2026-03-15T00:00:00Z",
  },
];

// Venue Photos
export const venuePhotos: VenuePhoto[] = [
  {
    id: "vp-braxton-1",
    venue_id: "venue-braxton",
    storage_path: "https://images.unsplash.com/photo-1559526324-593bc073d938?w=800&h=600&fit=crop",
    caption: "Braxton Brewing taproom entrance with ramp visible on the left side",
    photo_category: "entrance",
    alt_text: "Industrial-style brewery entrance with a concrete ramp leading to a heavy metal door. The ramp has no handrails and the door opens outward toward the ramp.",
    is_primary: true,
    sort_order: 0,
    uploaded_by: "profile-matthew",
    created_at: "2026-01-15T00:00:00Z",
  },
  {
    id: "vp-braxton-2",
    venue_id: "venue-braxton",
    storage_path: "https://images.unsplash.com/photo-1555658636-6e4a36218be7?w=800&h=600&fit=crop",
    caption: "Wide-open taproom interior with communal tables",
    photo_category: "interior",
    alt_text: "Spacious brewery interior with high ceilings, exposed brick walls, and long wooden communal tables at standard seating height. Wide aisles between tables.",
    is_primary: false,
    sort_order: 1,
    uploaded_by: "profile-matthew",
    created_at: "2026-01-15T00:00:00Z",
  },
  {
    id: "vp-aquarium-1",
    venue_id: "venue-aquarium",
    storage_path: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&h=600&fit=crop",
    caption: "Newport Aquarium main entrance with automatic doors",
    photo_category: "entrance",
    alt_text: "Modern building entrance with wide automatic glass doors, level threshold, and a covered walkway from the parking garage. Clear signage visible.",
    is_primary: true,
    sort_order: 0,
    uploaded_by: "profile-matthew",
    created_at: "2026-01-20T00:00:00Z",
  },
  {
    id: "vp-aquarium-2",
    venue_id: "venue-aquarium",
    storage_path: "https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=800&h=600&fit=crop",
    caption: "Shark tunnel exhibit with wide walkway",
    photo_category: "interior",
    alt_text: "Curved glass tunnel with sharks swimming overhead. The walkway is wide enough for two wheelchairs to pass side by side. Smooth, non-slip flooring throughout.",
    is_primary: false,
    sort_order: 1,
    uploaded_by: "profile-matthew",
    created_at: "2026-01-20T00:00:00Z",
  },
  {
    id: "vp-roebling-1",
    venue_id: "venue-roebling",
    storage_path: "https://images.unsplash.com/photo-1521017432531-fbd92d768814?w=800&h=600&fit=crop",
    caption: "Roebling Point Books & Coffee storefront with narrow entrance",
    photo_category: "entrance",
    alt_text: "Small independent bookstore and coffee shop with a traditional storefront. Two steps lead to the main door. A steep portable ramp leads to a narrow side door.",
    is_primary: true,
    sort_order: 0,
    uploaded_by: "profile-matthew",
    created_at: "2026-02-01T00:00:00Z",
  },
];

// Editorial Reviews
export const reviews: Review[] = [
  {
    id: "review-braxton",
    venue_id: "venue-braxton",
    author_id: "profile-matthew",
    is_editorial: true,
    title: "Braxton Brewing: Great Beer, Awkward Entrance, and a Bathroom That Almost Works",
    body: `Braxton's taproom looks great on Instagram. Wide open industrial space, communal tables, the whole craft brewery aesthetic. And from the parking lot, you'd think it's going to work. There's a ramp. It's even at a reasonable angle.

But here's the thing nobody tells you on Google: the ramp leads to a door that requires you to pull it toward you while simultaneously backing up your scooter on said ramp. Physics isn't on your side here. I've done it, but it took three tries and a stranger's help.

Once you're inside, it's actually pretty good. The tables are the right height, the aisles are wide enough, and the staff has always been genuinely helpful — not in a performative "oh you poor thing" way, but in a "hey, want me to grab that door?" way. That matters more than most people realize.

The bathroom is another story. There's an accessible stall with grab bars, which is a genuine effort. But the door swings inward, which means you need to back your chair in and then somehow close the door while you're inside it. The stall width is technically ADA-compliant but practically tight for a scooter. A wheelchair would fare better.

The beer is excellent, by the way. The Garage Beer is my go-to. Just bring a friend who can hold the front door.

## The Verdict

Braxton gets a **partially accessible** rating. The interior is genuinely good. The entrance is a physics problem that needs a $200 automatic door opener to fix. The bathroom is compliant but not comfortable. For scooter users specifically: go with a friend, and you'll have a great time.`,
    body_html: "",
    excerpt: "Braxton's taproom looks great on Instagram. But here's the thing nobody tells you on Google: the ramp leads to a door that requires you to pull it toward you while simultaneously backing up your scooter on said ramp.",
    overall_rating: "partially_accessible",
    visit_date: "2026-02-10",
    mobility_device_used: "scooter",
    published: true,
    featured: true,
    status: "approved",
    helpful_count: 24,
    created_at: "2026-02-15T00:00:00Z",
    updated_at: "2026-02-15T00:00:00Z",
  },
  {
    id: "review-aquarium",
    venue_id: "venue-aquarium",
    author_id: "profile-matthew",
    is_editorial: true,
    title: "Newport Aquarium: This Is How You Do It",
    body: `I'll cut straight to it: Newport Aquarium is one of the most accessible venues I've reviewed. Not "accessible for a tourist attraction" or "accessible with an asterisk." Just accessible.

It starts in the parking garage. Accessible spots on every level, right next to the elevators. The skybridge to the aquarium is level, covered, and wide. The entrance has automatic doors that actually work.

Inside, every exhibit is reachable. The tunnels — the glass shark tunnels that are the whole reason you're here — are wide enough for two wheelchairs to pass. The viewing windows come in multiple heights, so wheelchair users and kids aren't staring at someone else's back. The touch pools have lowered edges.

The elevators between levels are large and well-signed. Staff proactively offered to help with directions and held doors without being asked — and without making it weird. They have scooter rentals at the front desk, and a charging station near the cafe.

The restrooms are the gold standard. Family/accessible restrooms on every level. Spacious. Clean. Grab bars. Automatic sinks and dryers. This is what "accessible" actually looks like when someone designs for it instead of bolting it on as an afterthought.

## The Verdict

Newport Aquarium earns a full **accessible** rating. Every category — parking, entrance, interior, bathroom, scooter access — is genuinely good. If every venue in this city operated at this level, this website wouldn't need to exist.`,
    body_html: "",
    excerpt: "I'll cut straight to it: Newport Aquarium is one of the most accessible venues I've reviewed. Not 'accessible for a tourist attraction' or 'accessible with an asterisk.' Just accessible.",
    overall_rating: "accessible",
    visit_date: "2026-02-25",
    mobility_device_used: "scooter",
    published: true,
    featured: true,
    status: "approved",
    helpful_count: 42,
    created_at: "2026-03-01T00:00:00Z",
    updated_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "review-roebling",
    venue_id: "venue-roebling",
    author_id: "profile-matthew",
    is_editorial: true,
    title: "Roebling Point Books & Coffee: A Bookstore I Love That Doesn't Love Me Back",
    body: `Roebling Point is my favorite bookstore in Covington. The selection is curated, the coffee is good, and the owner knows books the way some people know wine. I want to recommend it unconditionally.

I can't.

The main entrance has two steps and no ramp. The side entrance has a ramp, but it's steep enough that I nearly tipped my scooter the first time I tried it. The door at the top of that ramp is narrow — I mean "sucking in your elbows" narrow. I can get through on my scooter, barely, but a standard power wheelchair would not make it.

Once inside, it's a bookstore. Bookshelves take up space. The aisles between them are maybe 28 inches wide in spots. I can browse the front section near the window, where there's a small seating area at normal table height. The back of the store and the far shelves? I've never reached them without asking someone to grab a book for me.

The bathroom is a hard no. Down a narrow hallway, the door barely opens wide enough for a walker, let alone anything on wheels. I've never attempted it.

The staff is wonderful. They'll grab books, move chairs, bring your coffee to the window seat. They clearly care. But caring doesn't widen doorways. This is a historic building problem, and I get that renovation isn't free. But a portable ramp with better slope and a wider side door would go a long way.

## The Verdict

**Partially accessible** — and I'm being generous because the staff effort is genuine. Walker users can manage with patience. Wheelchair and scooter users will need help at the entrance and will have limited access inside. The bathroom is not accessible. Go for the books and the coffee, but know what you're getting into.`,
    body_html: "",
    excerpt: "Roebling Point is my favorite bookstore in Covington. The selection is curated, the coffee is good, and the owner knows books. I want to recommend it unconditionally. I can't.",
    overall_rating: "partially_accessible",
    visit_date: "2026-02-20",
    mobility_device_used: "scooter",
    published: true,
    featured: false,
    status: "approved",
    helpful_count: 18,
    created_at: "2026-03-05T00:00:00Z",
    updated_at: "2026-03-05T00:00:00Z",
  },
];

// Review Photos
export const reviewPhotos: ReviewPhoto[] = [
  {
    id: "rp-braxton-1",
    review_id: "review-braxton",
    storage_path: "https://images.unsplash.com/photo-1559526324-593bc073d938?w=800&h=600&fit=crop",
    caption: "The ramp-to-door problem at Braxton's entrance",
    photo_category: "entrance",
    alt_text: "Brewery entrance showing a concrete ramp at roughly 1:8 slope leading to a heavy metal door that opens outward toward the person on the ramp, creating a conflict between door swing and ramp space.",
    sort_order: 0,
    created_at: "2026-02-15T00:00:00Z",
  },
  {
    id: "rp-braxton-2",
    review_id: "review-braxton",
    storage_path: "https://images.unsplash.com/photo-1555658636-6e4a36218be7?w=800&h=600&fit=crop",
    caption: "Wide interior aisles at Braxton",
    photo_category: "interior",
    alt_text: "Open brewery taproom with approximately 5-foot aisles between long communal tables. High ceilings and industrial decor. Plenty of room to navigate a scooter or wheelchair.",
    sort_order: 1,
    created_at: "2026-02-15T00:00:00Z",
  },
  {
    id: "rp-aquarium-1",
    review_id: "review-aquarium",
    storage_path: "https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=800&h=600&fit=crop",
    caption: "The shark tunnel — wide enough for two wheelchairs to pass",
    photo_category: "interior",
    alt_text: "Curved glass tunnel in the aquarium with sharks swimming overhead. The walkway is smooth concrete, approximately 8 feet wide, with gentle curves and no steps.",
    sort_order: 0,
    created_at: "2026-03-01T00:00:00Z",
  },
];

// Mobility Tips
export const mobilityTips: MobilityTip[] = [
  {
    id: "tip-braxton-1",
    venue_id: "venue-braxton",
    mobility_type: "scooter",
    tip: "Approach the ramp door at an angle so you can reach the handle while your scooter is pointed slightly away. Or just bring someone to hold it.",
    author_id: "profile-matthew",
    created_at: "2026-02-15T00:00:00Z",
  },
  {
    id: "tip-braxton-2",
    venue_id: "venue-braxton",
    mobility_type: "manual_wheelchair",
    tip: "The bathroom stall is workable for a standard wheelchair. Ask for the door to be propped if needed — staff is happy to help.",
    author_id: "profile-matthew",
    created_at: "2026-02-15T00:00:00Z",
  },
  {
    id: "tip-aquarium-1",
    venue_id: "venue-aquarium",
    mobility_type: "scooter",
    tip: "Ask about the scooter rental at the front desk. It saves your own battery for the drive home. Charging station is in the cafe area on level 2.",
    author_id: "profile-matthew",
    created_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "tip-aquarium-2",
    venue_id: "venue-aquarium",
    mobility_type: "power_wheelchair",
    tip: "All exhibits are accessible without any detours. The touch pools have lowered edges — you can reach everything from a chair.",
    author_id: "profile-matthew",
    created_at: "2026-03-01T00:00:00Z",
  },
  {
    id: "tip-roebling-1",
    venue_id: "venue-roebling",
    mobility_type: "walker",
    tip: "Use the main entrance (two steps) if you can manage steps with your walker. The side ramp is steeper than it looks and there's nothing to hold onto.",
    author_id: "profile-matthew",
    created_at: "2026-03-05T00:00:00Z",
  },
  {
    id: "tip-findlay-1",
    venue_id: "venue-findlay",
    mobility_type: "scooter",
    tip: "Go on a weekday morning if you can. Saturday market is packed and the aisles get blocked by shoppers. The outdoor area is cobblestone — bumpy but passable at low speed.",
    author_id: "profile-matthew",
    created_at: "2026-02-25T00:00:00Z",
  },
  {
    id: "tip-hofbrauhaus-1",
    venue_id: "venue-hofbrauhaus",
    mobility_type: "scooter",
    tip: "Call ahead and request an end-of-bench seat. The communal tables are long and the benches are fixed — you can't pull a chair out. End seat lets you park your scooter alongside.",
    author_id: "profile-matthew",
    created_at: "2026-03-05T00:00:00Z",
  },
];
